server:
  port: 7911
spring:
  application:
    name: litchi-comsumer-movie-feign-with-hystrix
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://root:root@localhost:8761/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true #这是一个坑，需要开启feign对hystrix的支持
management:
  security:
    enabled: false #spring boot 1.5 开始，默认为actuator开启了安全保护