server:
  port: 7910
spring:
  application:
    name: litchi-comsumer-movie
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://root:root@localhost:8761/eureka
  instance:
    prefer-ip-address: true
management:
  security:
    enabled: false #spring boot 1.5 开始，默认为actuator开启了安全保护