server:
  port: 7910
spring:
  application:
    name: litchi-comsumer-movie-feign
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://root:root@localhost:8761/eureka
  instance:
    prefer-ip-address: true